# Timer experiments
#

OBJS = 	../util/console.o ../util/clock.o \
		../util/sdram.o ../util/retarget.o \
		../util/sbrk.o

BINARY = mic

CFLAGS += -O0

DEVICE = STM32F469NI

include ../../Makefile.include

