/*
 * Discrete Fourier Transform
 *
 * To understand FFTs you need to understand DFTs and
 * this code applies the DFT using correlation to the
 * samples generated by data gen.
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <math.h>
#include "signal.h"

#define SAMP_SIZE 1024
#define SAMP_RATE 8192

float r_x[SAMP_SIZE / 2];
float i_x[SAMP_SIZE / 2];
float res_dft[SAMP_SIZE / 2];
int ri_len = SAMP_SIZE / 2;
float s_data[SAMP_SIZE];

void gen_data(int opt);

void
gen_data(int opt)
{
	sample_buffer	sb;
	float f, data_min, data_max;
	int	i, k;

	sb.data = s_data;
	sb.n = SAMP_SIZE;
	sb.r = SAMP_RATE;	/* 8 khz sample rate */

	/* clear sample data */
	memset(s_data, 0, sizeof(s_data));

	switch (opt) {
		case 3:
			/* waves smeared over bin size */
			for (i = 0; i < 9; i++) {
				add_cos(&sb, 32 * i + 64 + i, 1.5);
			}
			break;
		case 1:
			/* triangle wave */
			add_triangle(&sb, 100.0, 1.5);
			break;
		case 2:
			/* square wave */
			add_square(&sb, 100.0, 1.5);
			break;
		default:
			/* a C chord */
			add_cos(&sb, 130.81, 1.0);
			add_cos(&sb, 164.81, 1.0);
			add_cos(&sb, 196, 1.0);
			break;
	}
	data_min = data_max = 0;
	for (i = 0; i < sb.n; i++) {
		data_min = (*(sb.data + i) < data_min) ? *(sb.data+i) : data_min;
		data_max = (*(sb.data + i) > data_max) ? *(sb.data+i) : data_max;
	}
#ifdef DEBUG
	scale = 60.0 / (data_max - data_min);
	printf("Min/Max - %f, %f\n", data_min, data_max);
	printf("Scale/Offset - %f, %f\n", scale, offset);
#endif
	
	printf("Generating data ... \n");

	for (i = 1; i < SAMP_SIZE/2; i++) {
		float t;

		f = (float) (4096 * i) / 4096.0;
		r_x[i] = 0;
		i_x[i] = 0;
		for (k = 0; k < SAMP_SIZE; k++) {
			t = (float) k / (float) SAMP_RATE;
			r_x[i] += s_data[k] * cos_basis(f, t);
			i_x[i] += s_data[k] * sin_basis(f, t);
		}
		r_x[i] = (2 * r_x[i]) / (SAMP_SIZE / 2);
		i_x[i] = (-2 * i_x[i]) / (SAMP_SIZE / 2);
		printf("\r%d of %d ... ", i, SAMP_SIZE/2);
		fflush(stdout);
	}
	printf("Done.\n");
}
